Section "ServerLayout"
    Identifier "Mini"
    Screen 0 "Screen0"
    InputDevice "Kbd" "CoreKeyboard"
    InputDevice "Mse" "CorePointer"
EndSection

Section "InputDevice"
    Identifier "Kbd"
    Driver "evdev"
    Option "Device" "/dev/input/event0"
    Option "XkbRules" "xorg"
    Option "XkbModel" "pc105"
    Option "XkbLayout" "us"
EndSection

Section "InputDevice"
    Identifier "Mse"
    Driver "evdev"
    Option "Device" "/dev/input/event1"
    Option "CorePointer" "true"
EndSection

Section "Device"
    Identifier "fb"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "ShadowFB" "false"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "fb"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1280x800"
    EndSubSection
EndSection
